jobs:
  pull-request:
    requires: [~pr]
    steps:
      - screwdrv_8281_hack: export SD_ZIP_ARTIFACTS='false'
      - print_env: set
      - build: gmake ${SD_SETTING_MAKE_ARGS} platforms
      - test: gmake ${SD_SETTING_MAKE_ARGS} testcoverageplatforms
      - package: gmake ${SD_SETTING_MAKE_ARGS} package-release
      
  merge:
    requires: [~commit]
    steps:
      - screwdrv_8281_hack: export SD_ZIP_ARTIFACTS='false'
      - print_env: set
      - build: gmake ${SD_SETTING_MAKE_ARGS} platforms
      - test: gmake ${SD_SETTING_MAKE_ARGS} testcoverageplatforms
      - package: gmake ${SD_SETTING_MAKE_ARGS} package-release
      - dist_force_push: gmake dist_force_push
      - git_tag: gmake git_tag

shared:
  image: docker-registry.ops.yahoo.com:4443/storm/storm-ci-docker-image:latest
  annotations:
    screwdriver.cd/cpu: HIGH
    screwdriver.cd/ram: HIGH
  environment:
    USER_SHELL_BIN: bash
  settings:
    email:
      addresses: [ storm-devel@verizonmedia.com ]
      statuses: [ FAILURE ]
