platform: cpp

shared:
    settings:
        env.MVN_MAKE_OPTS: --batch-mode

    notifications:
        email: "storm-devel@oath.com"
    steps:
        dist_force_push:
            description: Push packages to dist
            command: gmake dist_force_push
        git_tag:
            description: Git tag after successful release
            command: gmake git_tag
    triggers:
        - sd@1007419
    plugins:
        coverage:
            enabled: false
        test_results:
            type: junit
            parameters:
                path: "my_test_results"

jobs:
  component:
    order: [environment, install-rpms, init, build, test, package, dist_force_push, git_tag]
    plugins:
      resource:
        high
  pull-request:
    order: [environment, install-rpms, init, build, test, package]
    plugins:
      resource:
        high
